server:
  http-port: 8000
  read-timeout: 60
  write-timeout: 60
app:
  app_name: cloudRestaurant

database:
  driver_name: "mysql"
  user: 'root'
  password: '123456'
  host: '127.0.0.1'
  port: '3306'
  db_name: 'cloud_restaurant'
  # 是否打印日志
  log-mode: true
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  table_prefix: 'c_'
  max_open_connect: 200
  max_idle_connect: 50

redis:
  host: '127.0.0.1'
  port: '6379'
  db: 1
  password:
  max_idle: 30
  max_active: 30
  idle_timeout: 200
  pool_size: 100
